spring:
  datasource:
    master:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
    severnt:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/severnt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
  servlet:
    context-path: /transaction
management:
  endpoints:
    web:
      exposure:
        include: info,beans